name: CI with Cache

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore cache - cache-7c4ebb7
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            node_modules
          key: cache-7c4ebb7

      - name: prime-cache-7c4ebb7
        run: echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"
